import React from "react";

// NOTE: The following script is auto-generated by https://utteranc.es/
//  <script
//    src="https://utteranc.es/client.js"
//    repo="peanut-lover/peanut-lover.github.io"
//    issue-term="pathname"
//    theme="github-light"
//    crossorigin="anonymous"
//    async
//  ></script>;

export default React.memo(() => (
  <section
    ref={(elem) => {
      if (!elem) {
        return;
      }
      const scriptElement = document.createElement("script");
      scriptElement.src = "https://utteranc.es/client.js";
      scriptElement.async = true;
      scriptElement.setAttribute("repo", "peanut-lover/peanut-lover.github.io");
      scriptElement.setAttribute("issue-term", "pathname");
      scriptElement.setAttribute("theme", "github-light");
      scriptElement.crossOrigin = "anonymous";
      elem.appendChild(scriptElement);
    }}
  />
));
