name: Build docusaurus and Deploy github page
on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 16

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Use Cache dependencies
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: |
          yarn cache clean
          yarn install
        if: steps.yarn-cache.outputs.cache-hit != 'true'

      - name: Create .env file
        run: |
          touch .env
          echo USE_SSH="true" >> .env
          echo GIT_USER="peanut-lover" >> .env
          echo CURRENT_BRANCH="main" >> .env
          echo GIT_PASS=${{ secrets.PERSONAL_ACCESS_TOKEN }} >> .env
          cat .env

      - name: Deploy
        run: |
          yarn deploy
